version: '3.7'

services:
  drupal:
    image: drupal:9-apache
    container_name: drupal
    ports:
      - 8080:80
    volumes:
      - ./drupal_data:/var/www/html
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db:3306
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=root
      - DRUPAL_DB_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

